version: '3.9'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  web:
    build: .
    environment:
      PORT: 4000
      DBHOST: db
      DBPASSWORD: pwd
      DBUSER: postgres
      DB: test
      DBPORT: 5432
    ports:
      - '4000:4000'
    depends_on:
      - db

volumes:
  data:
